/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import { Prisma, TaskStatus as PrismaTaskStatus } from "@prisma/client";

export class TaskStatusServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.TaskStatusCountArgs, "select">
  ): Promise<number> {
    return this.prisma.taskStatus.count(args);
  }

  async taskStatuses<T extends Prisma.TaskStatusFindManyArgs>(
    args: Prisma.SelectSubset<T, Prisma.TaskStatusFindManyArgs>
  ): Promise<PrismaTaskStatus[]> {
    return this.prisma.taskStatus.findMany<Prisma.TaskStatusFindManyArgs>(args);
  }
  async taskStatus<T extends Prisma.TaskStatusFindUniqueArgs>(
    args: Prisma.SelectSubset<T, Prisma.TaskStatusFindUniqueArgs>
  ): Promise<PrismaTaskStatus | null> {
    return this.prisma.taskStatus.findUnique(args);
  }
  async createTaskStatus<T extends Prisma.TaskStatusCreateArgs>(
    args: Prisma.SelectSubset<T, Prisma.TaskStatusCreateArgs>
  ): Promise<PrismaTaskStatus> {
    return this.prisma.taskStatus.create<T>(args);
  }
  async updateTaskStatus<T extends Prisma.TaskStatusUpdateArgs>(
    args: Prisma.SelectSubset<T, Prisma.TaskStatusUpdateArgs>
  ): Promise<PrismaTaskStatus> {
    return this.prisma.taskStatus.update<T>(args);
  }
  async deleteTaskStatus<T extends Prisma.TaskStatusDeleteArgs>(
    args: Prisma.SelectSubset<T, Prisma.TaskStatusDeleteArgs>
  ): Promise<PrismaTaskStatus> {
    return this.prisma.taskStatus.delete(args);
  }
}
